config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'pages#search'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 6, maximum:100}
  validates :description, presence: true, length: {minimum: 10, maximum:300}

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories 
  validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum:25}

end

app/models/user.rb
class User < ApplicationRecord
  before_save {email = self.email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum:25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensiticwe: false}, length: {maximum:105}, format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_user
    if !helpers.logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show,:edit,:update,:destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = helpers.current_user
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title,:description, :post, category_ids: [])
  end

  def require_same_user
    if helpers.current_user != @article.user && !helpers.current_user.admin?
      flash[:danger] = "You can only edit your own articles"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
     @categories = Category.paginate(page: params[:page], per_page: 3)
  end

  def new
    @category = Category.new

  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category was updated successfully"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 3)

  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !helpers.logged_in? || !helpers.current_user.admin?
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
    redirect_to articles_path if session[:user_id]
  end

  def about
  end

  def search
    if params[:search].blank?
      flash[:notice] = "Search field is empty"
      redirect_to root_path
    else
      parameter = params[:search].downcase
      @articles = Article.all.where("lower(title) LIKE ?", "%#{parameter}%").or(Article.all.where("lower(description) LIKE ?", "%#{parameter}%")).or(Article.all.where("lower(post) LIKE ?", "%#{parameter}%")).uniq
      if @articles.count == 0
        flash[:notice] = "No results found"
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Credentials do not match any user"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def show
    @articles = Article.where(:user_id => @user.id).paginate(page: params[:page], per_page: 3)
  end

  def destroy
    @user = User.find(user_params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by the user have been deleted."
    redirect_to users_path
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    #make first user the admin by default
    if User.all.count == 0
      @user.admin = true
    end

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}. You have successfully signed up."
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account was updated successfully"
      redirect_to @user
    else
      render 'edit'
    end

  end

  private

  def user_params
    params.require(:user).permit(:username,:email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if helpers.current_user != @user && !helpers.current_user.admin?
      flash[:danger] = "You can only edit your own profile"
      redirect_to root_path
    end
  end

  def require_admin
    if helpers.logged_in? && !helpers.current_user.admin?
      flash[:danger] = "You must be an admin to perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def image_for(user)
    image_tag 'image' + user.id.inspect, alt: user.username, class: "rounded shadow mx-auto d-block"
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]    
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container" >
  <% obj.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to article.user.username, user_path(article.user) %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <% if article.categories.any? %>
              <p>Categories: <%= render article.categories %> </p>
            <% end %>
            <%= link_to 'View', article_path(article), class: "btn btn-outline-success"%>
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, Edited <%= time_ago_in_words(article.updated_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit an Article</h1>

<%= render 'layouts/form'%>

  

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles Listing Page</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article', obj: @articles %> 
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new Article</h1>

<%= render 'layouts/form'%>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container" >
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%=  @article.user.username %>
          </div>
          <div class="card-body">

            <p class="card-text  text-left"><%= simple_format(@article.description) %></p>
            <p class="card-text  text-left"><%= simple_format(@article.post) %></p>
            <% if @article.categories.any? %>
              <p>Categories: <%= render @article.categories %> </p>
            <% end %>
            <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
              <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, Edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%=  link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<div class=container>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @category%>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="firm-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light mb-3" %>
          <div class="col-sm-10">
            <%=f.text_field  :name, class: "form-control shadow rounded", placeholder: "Category name" %>
          </div>
        </div>

        <div class="firm-group row justify-content-center"> 
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and Return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Listing all categories</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
<div class="container col-4">
  <% @categories.each do |category|%>
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-body">
        <h5 class="card-title"><%= link_to "#{category.name}", category_path(category)%></h5>
        <p><small><%= pluralize(category.articles.count, "article")%></small></p>
      </div>
    </div>
  <%  end %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4"><%= "Category: " + @category.name%></h1>

<% if logged_in? && current_user.admin? %>
  <span class="badge col-8 offset-md-2"><%= link_to "Edit Category", edit_category_path(@category) %></span>
<% end %>
<div class="flickr_pagination">
  <%= will_paginate @category_articles, :container => false %>
</div>
<%= render 'articles/article', obj: @category_articles %> 
<div class="flickr_pagination mb-4">
  <%= will_paginate @category_articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; 2020 Alpha Blog</small>
  </div>
</footer>

app/views/layouts/_form.html.erb
<div class=container>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @article%>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="firm-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light mb-3" %>
          <div class="col-sm-10">
            <%=f.text_field  :title, class: "form-control shadow rounded", placeholder: "Title of Article" %>
          </div>
        </div>

        <div class="firm-group row mb-3"> 
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%=f.text_area  :description, rows: 2, class: "form-control shadow rounded", placeholder: "Description of Article" %>
          </div>
        </div>

        <div class="firm-group row mb-3">
          <%= f.label :post, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%=f.text_area  :post, rows: 10, class: "form-control shadow rounded", placeholder: "Body of Article" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="input-group mb-3">
              <div class="col-10 offset-md-2">
                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                  <% cb.label(class: "checkbox-inline input_checkbox mr-2 text-light") {cb.check_box(class: "checkbox") + cb.text} %>
                <% end %>
              </div>
          </div>
        </div>

        <div class="firm-group row justify-content-center"> 
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and Return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <%  flash.each do |key, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'ALPHA BLOG', root_path, class: "navbar-brand", id: "logo"  %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class: "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? %>
                <%= link_to 'Create new Article', new_article_path, class: "dropdown-item"%>
              <% end %>
              <%= link_to 'View Articles', articles_path, class: "dropdown-item"%>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? && current_user.admin? %>
                <%= link_to 'Create new Category', new_category_path, class: "dropdown-item"%>
              <% end %>
              <%= link_to 'View Categories', categories_path, class: "dropdown-item"%>
            </div>
          </li>
          
          <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.admin? %>
                <%= current_user.username %> - Admin
              <%  else %>
                <%= current_user.username %>
              <% end %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit your profile', edit_user_path(current_user), class: "dropdown-item"%>
              <%= link_to 'View your profile', user_path(current_user), class: "dropdown-item"%>
            </div>
          </li>
          <% end %>

          <% if logged_in? %>
           <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete%>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", login_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", signup_path, class: "nav-link"%>
            </li>
          <% end %>
        </ul>

        <%= form_tag(search_path, :method => "get", class: 'form-inline my-2 my-lg-0') do %>
          <div class="input-group">
            <%= search_field_tag :search, params[:search], placeholder: "Search blog", class: "form-control mr-sm-2" %>
            <div class="input-group-btn">
              <%= button_tag "Search", :class => 'btn btn-outline-success my-2 my-sm-0',:name => nil %>
            </div>
          </div>
        <% end %>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    
    <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

    <%= render "layouts/footer"%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is an About Page</h1>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4 text-center">Alpha Blog</h1>
    <p class="lead text-center">Welcome to Alpha Blog, a simple blogging site.</p>
    <hr class="my-4">
    <p c;ass="text-center">To write your own blog, sign up!</p>
    <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

 

app/views/pages/search.html.erb
<h1 class="text-center mt-4">Search Results</h1>


<%= render 'articles/article', obj: @articles %>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved.</h4>
    <ul>
      <% obj.errors.full_messages.each do |e|%>
        <li><%= e %></li>
      <% end%>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end%>
    

app/views/users/_form.html.erb
<div class=container>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @user%>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="firm-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light mb-3" %>
          <div class="col-sm-10">
            <%=f.text_field  :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="firm-group row mb-3"> 
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%=f.email_field  :email, class: "form-control shadow rounded", placeholder: "Enter an email address" %>
          </div>
        </div>

         <div class="firm-group row mb-3"> 
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%=f.password_field  :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="firm-group row justify-content-center"> 
          <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
        </div>

      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and Return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit Your Profile</h1>

<%= render 'form'%>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container" >
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-sm-6 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%=  link_to user.username, user_path(user) %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to image_for(user), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to 'View profile', user, class: "btn btn-outline-success"%>
            <% if logged_in? && (user == current_user || current_user.admin?) %>
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info" %>
            <%  end %>
            <% if logged_in? && current_user.admin? %>
              <%= link_to 'Delete User', user_path(user), method: :delete, data: { confirm: "Delete this user and all of their articles?"}, class: "btn btn-outline-info" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Signup for Alpha Blog</h1>

<%= render 'form'%>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username  %>'s Profile</h1>

<%= image_for(@user) %>

<% if current_user == @user %>
  <div class="text-center mt-4"><%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %></div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article', obj: @articles %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>